### ISSUE TITLE
Mark homework 1, exercise 1,2 of Yuhui Wang

### ISSUE THREAD

**Issue by ywangflora** [ywangflora/stat679work#1] opened 2016-09-26 01:39 UTC
# @cecileane
# https://github.com/ywangflora/stat679work/commit/5a7d2e1106fee11e5f8c66171cfd6014ea8ffeff
# comments: I am Yuhui Wang who studied 679-1. Here is my version of hw1.

**Comment by cecileane** [comment] 2016-09-26 02:23
Great work! It would help me if you could add your real name to your github profile.

Here are a few suggestions for improvement on this homework.

## in hw1/readme.md:
- add a link to your sentence "I got the data from coursedata in the git". "git" is a software. "github" is a website, so you want to replace "git" by "github" and add the exact link that someone else should use to re-dowload the data.
- The sentence "In log directory, I change all file names timetesty_snaq.log to timetest0y_snaq.log where "y" is a digit between 1 and 9." explains the result of what you did, but does not explain how. Provide the exact command to reproduce that.
- same for .out files.
- you need a blank line before "## exercise2", for this to turn into a header. Please visualize the result (html) of your readme file on github, [here](https://github.com/ywangflora/stat679work/blob/master/hw1/readme.md
- In your second paragraph, provide the exact command to reproduce the work (i.e. to execute your script `summarizeSNaQres.sh`. _After_ that, say "This is what the script does:" and put your explanation (I used `grep` ...) after.

PS: I'm using the markdown style to write this message. Take advantage of it to add code and links in your readme file.

## script `summarizeSNaQres.sh`

I can reconstruct the result `.csv` file when I run your script, but I also get the errors below. Could you please fix them?

``` shell
$ bash summarizeSNaQres.sh 
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
grep: ./out/.out: No such file or directory
```

**Comment by cecileane** [comment] 2016-09-26 02:30
about your `normalizeFileNames.sh` script:
- it would be best to document from which directory to run it from.
- a better option to make sure that the variable `$number` is correctly used by the shell is to do this:
  `timetest${number}_snaq.log` instead of `timetest$number\_snaq.log`. Your latter choice uses a trick that is not going to work generally. But using `${variableName}` would work generally.

**Comment by cecileane** [comment] 2016-09-26 02:41
Next time, put your work here using shell commands (`git push` etc.), not via upload (according to your commit message). We have not covered these `git push` and `git pull` commands in class yet! But by next time, we will have seen it in class.

You might run into problems if you change your github repository one way (via one or more uploads of some files) and change your local repository (on your laptop) a different way (via commit of some files, but may be not the exact same list of files, and maybe not in a single commit). If you get into trouble later when you do `git push`, come see me to fix the issue and to re-synchronize your 2 repositories: on your laptop, and here on github. They need to have the exact same "snapshots" of your work (commits).

**Comment by ywangflora** [comment] 2016-09-27 01:42
Hi professor,

Thank you for the response. 

For the script `summarizeSNaQres.sh`, I submitted a previous version. Sorry for the mistake. The following part is the correct script summarizeSNaQres.sh. Because the due time is tomorrow, will this mistake affect the final grades on hw1?

``` r
echo analysis, h, CPUtime > summarizeSNaQres.csv   # add the name of the columns

for filename in ./log/*.log                        # for loop to search log file in certain directory
    do
    analysis=`echo $filename | cut -f 2 -d'.' | cut -f 3 -d'/'`   # get the name of the file
    h=`grep 'hmax\s=\s\d' $filename | grep -o '\d'`               # get hmax
    o=`echo ./out/$analysis\.out`                                 # get the relative path to the out file
    c=`grep 'Elapsed\stime' $o | grep -oE "\d+\.\d+"`             # get CPUtime
    echo $analysis, $h, $c >> summarizeSNaQres.csv                # display in a csv file
    done
```

**Comment by ywangflora** [comment] 2016-09-27 01:49
Hi professor, 

I understood the advice you gave me to improve my readme file. Should l upload a new version of readme file to show the changes I made?

**Comment by cecileane** [comment] 2016-09-27 01:52
Hi Yuhui, great! you will need to commit this new version to your local git repository on your laptop, and then push to github, so that your new version goes into your repository and not this discussion. You do _not_ need to do this for tomorrow. Submitting your work and using git for submission is for Thursday. No worry. We will talk about git in detail tomorrow in class, so no need to worry today if some of the terminology in my message doesn't sense yet. Do _not_ upload your new files. We will learn how to "push" them from the command line.

You just used markdown style in your message, this is very nice.

**Comment by ywangflora** [comment] 2016-09-27 01:57
Hi professor! I got error when I did `git push` on the terminal. Here is the error message I got. Could you tell me how to solve the problem?

``` r
wangyuhuideMacBook-Pro-2:hw1 wangyuhui$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

To git@github.com:ywangflora/stat679work.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:ywangflora/stat679work.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by cecileane** [comment] 2016-09-27 03:15
Hi Yuhui, just 2 things, because there are 2 issues with the output above.
- please wait until tomorrow: we will talk about git tomorrow. (first error: your `git push` command is incomplete given your configuration, and your configuration is good: it's safe).
- the second and more problematic error is what I wrote about earlier (my 3rd message from yesterday). It's the consequence of you uploading files via a browser. You will need to come see me to make sure that you do not lose work when you try to fix this problem.

Keep your files as you want them to be on your laptop, and come see me when you can, preferably after today's class (like during my office hours on Wednesday).

**Comment by cecileane** [comment] 2016-10-05 16:29
No need to open a new issue next time. Just add a new comment to say that you work is finished and ready to be graded. thanks!

**Comment by cecileane** [comment] 2016-10-05 16:30
Please close this issue now, since you opened a new one.

**Closed as completed** 2016-10-10 18:58 UTC
